# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faltas_Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alumno', models.CharField(max_length=50)),
                ('Curso', models.CharField(max_length=50)),
                ('Unidad', models.CharField(max_length=50)),
                ('Materia', models.CharField(max_length=50)),
                ('FechaDesde', models.DateField(blank=True)),
                ('FechaHasta', models.DateField(blank=True)),
                ('TotalPeriodo', models.IntegerField(blank=True, null=True)),
                ('HorasLectivas', models.IntegerField(blank=True, null=True)),
                ('JustificadasHoras', models.IntegerField(blank=True, null=True)),
                ('JustificadasPorcentaje', models.FloatField(blank=True, null=True)),
                ('InjustificadasHoras', models.IntegerField(blank=True, null=True)),
                ('InjustificadasPorcentaje', models.FloatField(blank=True, null=True)),
                ('Retrasos', models.IntegerField(blank=True, null=True)),
                ('Estado', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['Alumno'],
                'verbose_name_plural': 'Falta_Asistencia',
            },
        ),
        migrations.CreateModel(
            name='Pdfs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombrePdf', models.CharField(max_length=50)),
                ('Estado', models.CharField(max_length=10)),
                ('FechaSubida', models.DateField(auto_now_add=True)),
                ('FechaProces', models.DateField(blank=True, null=True)),
                ('pdf', models.FileField(upload_to=b'pdfs')),
            ],
            options={
                'ordering': ['NombrePdf'],
                'verbose_name_plural': 'Pdfs',
            },
        ),
    ]
