# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faltas_asistencia',
            name='Estado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pdfs',
            name='Estado',
            field=models.CharField(max_length=50),
        ),
    ]
