# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_auto_20180322_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faltas_asistencia',
            name='Materia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faltas_asistencia',
            name='Unidad',
            field=models.CharField(max_length=100),
        ),
    ]
